Se importan las librerias que se crean necesarias

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# 1 dataset ConectividadalserviciodeInternet_2776151689464931014.csv

Se instancia el dataset como un dataframe en la variable conectividad

In [154]:
conectividad = pd.read_csv('Datasets_originales\ConectividadalserviciodeInternet_2776151689464931014.csv')
conectividad

Provincia       Partido        Localidad  Poblacion ADSL CABLEMODEM  \
0     BUENOS AIRES  Bahía Blanca    Villa Bordeau          0   --         --   
1     BUENOS AIRES  Bahía Blanca     Villa Espora          0   --         --   
2     BUENOS AIRES      Balcarce         Balcarce      38376   SI         SI   
3     BUENOS AIRES      Balcarce        Los Pinos        337   --         --   
4     BUENOS AIRES      Balcarce        Napaleofú        374   --         --   
...            ...           ...              ...        ...  ...        ...   
4307         CHACO     Quitilipi        Quitilipi      24517   SI         --   
4308         CHACO     Quitilipi  Villa El Palmar        879   --         --   
4309         CHACO  San Fernando     Barranqueras      54698   SI         SI   
4310         CHACO  San Fernando           Basail       1929   SI         SI   
4311         CHACO  San Fernando  Colonia Baranda        336   --         --   

     DIALUP FIBRAOPTICA SATELITAL WIRELESS TELEFONIAFIJA  3G  4G        link  \
0        --          --        --       --            --  SI  SI   6056020.0   
1        --          --        --       --            --  --  --   6056020.0   
2        SI          SI        --       SI            SI  SI  SI   6063010.0   
3        --          --        --       SI            SI  --  --   6063020.0   
4        --          SI        --       SI            SI  SI  SI   6063030.0   
...     ...         ...       ...      ...           ...  ..  ..         ...   
4307     --          SI        --       SI            SI  SI  SI  22133010.0   
4308     --          --        --       SI            --  --  SI  22133020.0   
4309     --          SI        --       SI            SI  SI  SI  22140010.0   
4310     --          --        SI       SI            SI  SI  SI  22140020.0   
4311     --          --        --       --            --  SI  SI  22140030.0   

                Latitud           Longitud  
0     -38,6472605094596  -62,3200223419024  
1     -38,7765069529222  -62,1851833537179  
2     -37,8482779294345  -58,2551665841248  
3        -37,9412057603  -58,3225920150442  
4     -37,6254980210026  -58,7461862359423  
...                 ...                ...  
4307  -26,8732071732978  -60,2185241226399  
4308  -26,4551186226266  -60,1646165913523  
4309  -27,4877739289761  -58,9327416886365  
4310  -27,8868655966917  -59,2791003619491  
4311  -27,5620449432874  -59,3096911774268  

[4312 rows x 16 columns]

In [155]:
conectividad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4312 entries, 0 to 4311
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Provincia      4312 non-null   object 
 1   Partido        4312 non-null   object 
 2   Localidad      4312 non-null   object 
 3   Poblacion      4312 non-null   int64  
 4   ADSL           4312 non-null   object 
 5   CABLEMODEM     4312 non-null   object 
 6   DIALUP         4312 non-null   object 
 7   FIBRAOPTICA    4312 non-null   object 
 8   SATELITAL      4312 non-null   object 
 9   WIRELESS       4312 non-null   object 
 10  TELEFONIAFIJA  4312 non-null   object 
 11  3G             4312 non-null   object 
 12  4G             4312 non-null   object 
 13  link           4300 non-null   float64
 14  Latitud        4312 non-null   object 
 15  Longitud       4312 non-null   object 
dtypes: float64(1), int64(1), object(14)
memory usage: 539.1+ KB


Se identifican las filas con valores duplicados en las columnas 'Provincia', 'Partido' y 'Localidad' para determinar las ubicaciones que se repiten

In [156]:
duplicados = conectividad.duplicated(subset=['Provincia', 'Partido', 'Localidad'], keep=False)
filas_duplicadas = conectividad[duplicados]
filas_duplicadas

Provincia       Partido        Localidad  Poblacion ADSL CABLEMODEM  \
200     ENTRE RIOS         Colón           Hocker         98   --         --   
243     ENTRE RIOS         Colón           Hocker          0   --         --   
650        TUCUMAN     Cruz Alta         Lastenia          0   --         --   
651        TUCUMAN     Cruz Alta         Lastenia          0   --         --   
1632     RIO NEGRO  General Roca  Barrio La Costa         94   --         --   
1633     RIO NEGRO  General Roca  Barrio La Costa         94   --         --   
2385    ENTRE RIOS        Paraná       El Ramblón          0   --         --   
2386    ENTRE RIOS        Paraná       El Ramblón          0   --         --   
3365  BUENOS AIRES      La Plata     ruta del sol          0   SI         --   
3366  BUENOS AIRES      La Plata     ruta del sol       2312   SI         --   
4121      LA RIOJA     Sanagasta  Villa Sanagasta       2275   --         --   
4122      LA RIOJA     Sanagasta  Villa Sanagasta          0   --         SI   

     DIALUP FIBRAOPTICA SATELITAL WIRELESS TELEFONIAFIJA  3G  4G        link  \
200      --          --        --       SI            --  --  SI  30008100.0   
243      --          --        --       --            --  --  SI  30008100.0   
650      --          --        --       --            --  SI  SI  90014090.0   
651      --          --        --       --            --  SI  SI  90014090.0   
1632     --          --        --       --            --  --  --  62042200.0   
1633     --          --        --       SI            --  --  --  62042200.0   
2385     --          --        --       --            --  --  SI  30084095.0   
2386     --          --        --       SI            --  --  SI  30084095.0   
3365     --          --        --       --            --  SI  SI   6441050.0   
3366     --          --        --       --            --  SI  SI   6441050.0   
4121     --          --        --       --            --  SI  SI  46126010.0   
4122     --          SI        SI       SI            SI  SI  SI  46126010.0   

                Latitud           Longitud  
200   -32,0874958453901  -58,3417058444451  
243   -32,0874958453901  -58,3417058444451  
650   -26,8621611908602  -65,1625825810305  
651   -26,8498779490703  -65,1293137289629  
1632  -39,0753070627553  -67,5392261916358  
1633  -39,0753070627553  -67,5392261916358  
2385  -31,8480473768248  -60,0927487719843  
2386  -31,8480473768248  -60,0927487719843  
3365  -34,9437333541431  -58,1732652389706  
3366  -34,9437333541431  -58,1732652389706  
4121  -29,3064491456943  -67,0414097362521  
4122  -29,3064491456943  -67,0414097362521

Se eliminan las filas que no se consideran importantes

In [157]:
conectividad.drop([243, 651, 1632, 2385, 3365], inplace=True)

Se pasa el valor de población de la fila 4121 en donde no se refleja que tipos de conección hay en la localidad a la fila 4122 donde si se ven reflejados pero falta el dato poblacional

In [158]:
valor_poblacion_4121 = conectividad.at[4121, 'Poblacion']

In [159]:
conectividad.at[4122, 'Poblacion'] = valor_poblacion_4121

Y ahora si se elimina la fila que no se considera relevante

In [160]:
conectividad.drop([4121], inplace=True)

Se vuelve a revisar si hay lugares duplicados y se comprueba que no

In [161]:
duplicados = conectividad.duplicated(subset=['Provincia', 'Partido', 'Localidad'], keep=False)
filas_duplicadas = conectividad[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Provincia, Partido, Localidad, Poblacion, ADSL, CABLEMODEM, DIALUP, FIBRAOPTICA, SATELITAL, WIRELESS, TELEFONIAFIJA, 3G, 4G, link, Latitud, Longitud]
Index: []

Cambiar de tipo de dato de las columnas Latitud y longitud

Se reemplazan algunos puntos que no van por comas

In [162]:
conectividad['Latitud'] = conectividad['Latitud'].str.replace('.', '')

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\3168584693.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  conectividad['Latitud'] = conectividad['Latitud'].str.replace('.', '')


In [163]:
conectividad['Longitud'] = conectividad['Longitud'].str.replace('.', '')

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\2558316873.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  conectividad['Longitud'] = conectividad['Longitud'].str.replace('.', '')


Se cambian las comas por puntos

In [164]:
conectividad['Latitud'] = conectividad['Latitud'].str.replace(',', '.')

In [165]:
conectividad['Longitud'] = conectividad['Longitud'].str.replace(',', '.')

Se transforman las columnas en numericas

In [166]:
conectividad['Latitud'] = pd.to_numeric(conectividad['Latitud'])

In [167]:
conectividad['Longitud'] = pd.to_numeric(conectividad['Longitud'])

Cambiar los datos de las columnas ADSL, CABLEMODEM, DIALUP, FIBRAOPTICA, SATELITAL, WIRELESS, TELEFONIAFIJA, 3G y 4G de si y -- a 1 y 0

In [168]:
conectividad[['ADSL', 'CABLEMODEM', 'DIALUP', 'FIBRAOPTICA', 'SATELITAL', 'WIRELESS', 'TELEFONIAFIJA', '3G', '4G']] = conectividad[['ADSL', 'CABLEMODEM', 'DIALUP', 'FIBRAOPTICA', 'SATELITAL', 'WIRELESS', 'TELEFONIAFIJA', '3G', '4G']].replace({'SI': 1, '--': 0})

In [169]:
conectividad.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4306 entries, 0 to 4311
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Provincia      4306 non-null   object 
 1   Partido        4306 non-null   object 
 2   Localidad      4306 non-null   object 
 3   Poblacion      4306 non-null   int64  
 4   ADSL           4306 non-null   int64  
 5   CABLEMODEM     4306 non-null   int64  
 6   DIALUP         4306 non-null   int64  
 7   FIBRAOPTICA    4306 non-null   int64  
 8   SATELITAL      4306 non-null   int64  
 9   WIRELESS       4306 non-null   int64  
 10  TELEFONIAFIJA  4306 non-null   int64  
 11  3G             4306 non-null   int64  
 12  4G             4306 non-null   int64  
 13  link           4294 non-null   float64
 14  Latitud        4306 non-null   float64
 15  Longitud       4306 non-null   float64
dtypes: float64(3), int64(10), object(3)
memory usage: 571.9+ KB


Se elimina las filas donde la población es 0, ya que se considera que estas filas van a afectar de mala manera a los resultados del análisis

In [170]:
conectividad = conectividad.drop(conectividad[conectividad['Poblacion'] == 0].index)

In [171]:
conectividad

Provincia       Partido        Localidad  Poblacion  ADSL  \
2     BUENOS AIRES      Balcarce         Balcarce      38376     1   
3     BUENOS AIRES      Balcarce        Los Pinos        337     0   
4     BUENOS AIRES      Balcarce        Napaleofú        374     0   
5     BUENOS AIRES      Balcarce      Ramos Otero         95     0   
6     BUENOS AIRES      Balcarce      San Agustín        498     0   
...            ...           ...              ...        ...   ...   
4307         CHACO     Quitilipi        Quitilipi      24517     1   
4308         CHACO     Quitilipi  Villa El Palmar        879     0   
4309         CHACO  San Fernando     Barranqueras      54698     1   
4310         CHACO  San Fernando           Basail       1929     1   
4311         CHACO  San Fernando  Colonia Baranda        336     0   

      CABLEMODEM  DIALUP  FIBRAOPTICA  SATELITAL  WIRELESS  TELEFONIAFIJA  3G  \
2              1       1            1          0         1              1   1   
3              0       0            0          0         1              1   0   
4              0       0            1          0         1              1   1   
5              0       0            0          0         1              0   0   
6              0       0            0          0         1              1   0   
...          ...     ...          ...        ...       ...            ...  ..   
4307           0       0            1          0         1              1   1   
4308           0       0            0          0         1              0   0   
4309           1       0            1          0         1              1   1   
4310           1       0            0          1         1              1   1   
4311           0       0            0          0         0              0   1   

      4G        link    Latitud   Longitud  
2      1   6063010.0 -37.848278 -58.255167  
3      0   6063020.0 -37.941206 -58.322592  
4      1   6063030.0 -37.625498 -58.746186  
5      1   6063040.0 -37.542635 -58.340719  
6      0   6063050.0 -38.012284 -58.355378  
...   ..         ...        ...        ...  
4307   1  22133010.0 -26.873207 -60.218524  
4308   1  22133020.0 -26.455119 -60.164617  
4309   1  22140010.0 -27.487774 -58.932742  
4310   1  22140020.0 -27.886866 -59.279100  
4311   1  22140030.0 -27.562045 -59.309691  

[3765 rows x 16 columns]

# 2 dataset Internet_Penetracion (1).csv

Se instancia el dataset como un dataframe en la variable penetracion

In [56]:
penetracion = pd.read_csv('Datasets/Internet_Penetracion (1).csv')
penetracion

Año  Trimestre Accesos por cada 100 hogares Accesos por cada 100 hab  \
0   2022          3                        76,64                    23,95   
1   2022          2                        75,97                    23,72   
2   2022          1                        73,88                    23,05   
3   2021          4                        73,18                    22,81   
4   2021          3                        70,58                    21,98   
5   2021          2                        69,24                    21,55   
6   2021          1                        67,95                    21,13   
7   2020          4                        67,62                    21,01   
8   2020          3                        66,31                    20,59   
9   2020          2                        64,21                    19,92   
10  2020          1                        62,86                    19,48   
11  2019          4                        62,92                    19,49   
12  2019          3                        65,79                    20,36   
13  2019          2                        64,53                    19,96   
14  2019          1                        62,48                    19,31   
15  2018          4                        61,42                    18,97   
16  2018          3                        60,69                    18,73   
17  2018          2                        59,16                    18,24   
18  2018          1                        58,82                    18,12   
19  2017          4                        57,78                    17,79   
20  2017          3                         56,9                    17,51   
21  2017          2                         54,9                    16,88   
22  2017          1                        54,16                    16,64   
23  2016          4                        53,94                    16,56   
24  2016          3                        53,73                     16,5   
25  2016          2                        53,34                    16,37   
26  2016          1                        51,85                     15,9   
27  2015          4                        52,63                    16,12   
28  2015          3                        52,46                    16,05   
29  2015          2                        51,76                    15,82   
30  2015          1                        51,36                    15,68   
31  2014          4                         50,5                    15,39   
32  2014          3                        50,67                    15,43   
33  2014          2                        49,86                    15,16   
34  2014          1                        49,55                    15,05   

          Periodo  
0   Jul-Sept 2022  
1    Abr-Jun 2022  
2    Ene-Mar 2022  
3    Oct-Dic 2021  
4   Jul-Sept 2021  
5    Abr-Jun 2021  
6    Ene-Mar 2021  
7    Oct-Dic 2020  
8   Jul-Sept 2020  
9    Abr-Jun 2020  
10   Ene-Mar 2020  
11   Oct-Dic 2019  
12  Jul-Sept 2019  
13   Abr-Jun 2019  
14   Ene-Mar 2019  
15   Oct-Dic 2018  
16  Jul-Sept 2018  
17   Abr-Jun 2018  
18   Ene-Mar 2018  
19   Oct-Dic 2017  
20  Jul-Sept 2017  
21   Abr-Jun 2017  
22   Ene-Mar 2017  
23   Oct-Dic 2016  
24  Jul-Sept 2016  
25   Abr-Jun 2016  
26   Ene-Mar 2016  
27   Oct-Dic 2015  
28  Jul-Sept 2015  
29   Abr-Jun 2015  
30   Ene-Mar 2015  
31   Oct-Dic 2014  
32  Jul-Sept 2014  
33   Abr-Jun 2014  
34   Ene-Mar 2014

Se analiza si hay datos duplicados

In [72]:
duplicados = penetracion.duplicated(subset=['Periodo'], keep=False)
filas_duplicadas = penetracion[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Año, Trimestre, Accesos por cada 100 hogares, Accesos por cada 100 hab, Periodo]
Index: []

In [57]:
penetracion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   Año                           35 non-null     int64 
 1   Trimestre                     35 non-null     int64 
 2   Accesos por cada 100 hogares  35 non-null     object
 3   Accesos por cada 100 hab      35 non-null     object
 4   Periodo                       35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB


Se decide pasar el tipo de dato en las columnas Accesos por cada 100 hogares y Accesos por cada 100 hab de Object a float

Primero se debe cambiar las ',' por '.' para que se pueda pasar a tipo de dato numérico

In [58]:
penetracion['Accesos por cada 100 hogares'] = penetracion['Accesos por cada 100 hogares'].str.replace(',', '.')

In [59]:
penetracion['Accesos por cada 100 hab'] = penetracion['Accesos por cada 100 hab'].str.replace(',', '.')

Luego se pasa a realizar el cambio anteriormente dicho

In [60]:
penetracion['Accesos por cada 100 hogares'] = pd.to_numeric(penetracion['Accesos por cada 100 hogares'])

In [61]:
penetracion['Accesos por cada 100 hab'] = pd.to_numeric(penetracion['Accesos por cada 100 hab'])

In [62]:
penetracion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Año                           35 non-null     int64  
 1   Trimestre                     35 non-null     int64  
 2   Accesos por cada 100 hogares  35 non-null     float64
 3   Accesos por cada 100 hab      35 non-null     float64
 4   Periodo                       35 non-null     object 
dtypes: float64(2), int64(2), object(1)
memory usage: 1.5+ KB


In [69]:
penetracion

Año  Trimestre  Accesos por cada 100 hogares  Accesos por cada 100 hab  \
0   2022          3                         76.64                     23.95   
1   2022          2                         75.97                     23.72   
2   2022          1                         73.88                     23.05   
3   2021          4                         73.18                     22.81   
4   2021          3                         70.58                     21.98   
5   2021          2                         69.24                     21.55   
6   2021          1                         67.95                     21.13   
7   2020          4                         67.62                     21.01   
8   2020          3                         66.31                     20.59   
9   2020          2                         64.21                     19.92   
10  2020          1                         62.86                     19.48   
11  2019          4                         62.92                     19.49   
12  2019          3                         65.79                     20.36   
13  2019          2                         64.53                     19.96   
14  2019          1                         62.48                     19.31   
15  2018          4                         61.42                     18.97   
16  2018          3                         60.69                     18.73   
17  2018          2                         59.16                     18.24   
18  2018          1                         58.82                     18.12   
19  2017          4                         57.78                     17.79   
20  2017          3                         56.90                     17.51   
21  2017          2                         54.90                     16.88   
22  2017          1                         54.16                     16.64   
23  2016          4                         53.94                     16.56   
24  2016          3                         53.73                     16.50   
25  2016          2                         53.34                     16.37   
26  2016          1                         51.85                     15.90   
27  2015          4                         52.63                     16.12   
28  2015          3                         52.46                     16.05   
29  2015          2                         51.76                     15.82   
30  2015          1                         51.36                     15.68   
31  2014          4                         50.50                     15.39   
32  2014          3                         50.67                     15.43   
33  2014          2                         49.86                     15.16   
34  2014          1                         49.55                     15.05   

          Periodo  
0   Jul-Sept 2022  
1    Abr-Jun 2022  
2    Ene-Mar 2022  
3    Oct-Dic 2021  
4   Jul-Sept 2021  
5    Abr-Jun 2021  
6    Ene-Mar 2021  
7    Oct-Dic 2020  
8   Jul-Sept 2020  
9    Abr-Jun 2020  
10   Ene-Mar 2020  
11   Oct-Dic 2019  
12  Jul-Sept 2019  
13   Abr-Jun 2019  
14   Ene-Mar 2019  
15   Oct-Dic 2018  
16  Jul-Sept 2018  
17   Abr-Jun 2018  
18   Ene-Mar 2018  
19   Oct-Dic 2017  
20  Jul-Sept 2017  
21   Abr-Jun 2017  
22   Ene-Mar 2017  
23   Oct-Dic 2016  
24  Jul-Sept 2016  
25   Abr-Jun 2016  
26   Ene-Mar 2016  
27   Oct-Dic 2015  
28  Jul-Sept 2015  
29   Abr-Jun 2015  
30   Ene-Mar 2015  
31   Oct-Dic 2014  
32  Jul-Sept 2014  
33   Abr-Jun 2014  
34   Ene-Mar 2014

# 3 dataset historico_velocidad_internet.csv

Se instancia el dataset como un dataframe en la variable historico_velocidad_internet

In [63]:
historico_velocidad_internet = pd.read_csv('Datasets/historico_velocidad_internet.csv')
historico_velocidad_internet

Año  Trimestre Mbps (Media de bajada)    Trimestre.1
0   2022          3                  62,46  Jul-Sept 2022
1   2022          2                  58,44   Abr-Jun 2022
2   2022          1                  55,11   Ene-Mar 2022
3   2021          4                  52,34   Oct-Dic 2021
4   2021          3                  48,46  Jul-Sept 2021
5   2021          2                  45,63   Abr-Jun 2021
6   2021          1                  43,11   Ene-Mar 2021
7   2020          4                  42,36   Oct-Dic 2020
8   2020          3                  40,67  Jul-Sept 2020
9   2020          2                  38,32   Abr-Jun 2020
10  2020          1                  37,52   Ene-Mar 2020
11  2019          4                  28,26   Oct-Dic 2019
12  2019          3                  24,18  Jul-Sept 2019
13  2019          2                  20,33   Abr-Jun 2019
14  2019          1                  17,38   Ene-Mar 2019
15  2018          4                  15,95   Oct-Dic 2018
16  2018          3                  15,36  Jul-Sept 2018
17  2018          2                  13,85   Abr-Jun 2018
18  2018          1                  13,22   Ene-Mar 2018
19  2017          4                  12,01   Oct-Dic 2017
20  2017          3                   8,34  Jul-Sept 2017
21  2017          2                   7,16   Abr-Jun 2017
22  2017          1                   6,62   Ene-Mar 2017
23  2016          4                   6,34   Oct-Dic 2016
24  2016          3                   5,94  Jul-Sept 2016
25  2016          2                   5,42   Abr-Jun 2016
26  2016          1                   5,08   Ene-Mar 2016
27  2015          4                   4,99   Oct-Dic 2015
28  2015          3                   4,79  Jul-Sept 2015
29  2015          2                   4,55   Abr-Jun 2015
30  2015          1                   4,35   Ene-Mar 2015
31  2014          4                   4,16   Oct-Dic 2014
32  2014          3                   3,87  Jul-Sept 2014
33  2014          2                   3,76   Abr-Jun 2014
34  2014          1                   3,62   Ene-Mar 2014

In [64]:
historico_velocidad_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Año                     35 non-null     int64 
 1   Trimestre               35 non-null     int64 
 2   Mbps (Media de bajada)  35 non-null     object
 3   Trimestre.1             35 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.2+ KB


Se analiza si hay datos duplicados

In [73]:
duplicados = historico_velocidad_internet.duplicated(subset=['Trimestre.1'], keep=False)
filas_duplicadas = historico_velocidad_internet[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Año, Trimestre, Mbps (Media de bajada), Trimestre.1]
Index: []

Se cambia el tipo de dato de la columna Mbps (Media de bajada) de tipo object a float

In [65]:
historico_velocidad_internet['Mbps (Media de bajada)'] = historico_velocidad_internet['Mbps (Media de bajada)'].str.replace(',', '.')

In [66]:
historico_velocidad_internet['Mbps (Media de bajada)'] = pd.to_numeric(historico_velocidad_internet['Mbps (Media de bajada)'])

Se cambia el nombre de la columna Trimestre.1 por Periodo

In [79]:
historico_velocidad_internet.rename(columns={'Trimestre.1': 'Periodo'}, inplace=True)

In [80]:
historico_velocidad_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Año                     35 non-null     int64  
 1   Trimestre               35 non-null     int64  
 2   Mbps (Media de bajada)  35 non-null     float64
 3   Periodo                 35 non-null     object 
dtypes: float64(1), int64(2), object(1)
memory usage: 1.2+ KB


In [81]:
historico_velocidad_internet

Año  Trimestre  Mbps (Media de bajada)        Periodo
0   2022          3                   62.46  Jul-Sept 2022
1   2022          2                   58.44   Abr-Jun 2022
2   2022          1                   55.11   Ene-Mar 2022
3   2021          4                   52.34   Oct-Dic 2021
4   2021          3                   48.46  Jul-Sept 2021
5   2021          2                   45.63   Abr-Jun 2021
6   2021          1                   43.11   Ene-Mar 2021
7   2020          4                   42.36   Oct-Dic 2020
8   2020          3                   40.67  Jul-Sept 2020
9   2020          2                   38.32   Abr-Jun 2020
10  2020          1                   37.52   Ene-Mar 2020
11  2019          4                   28.26   Oct-Dic 2019
12  2019          3                   24.18  Jul-Sept 2019
13  2019          2                   20.33   Abr-Jun 2019
14  2019          1                   17.38   Ene-Mar 2019
15  2018          4                   15.95   Oct-Dic 2018
16  2018          3                   15.36  Jul-Sept 2018
17  2018          2                   13.85   Abr-Jun 2018
18  2018          1                   13.22   Ene-Mar 2018
19  2017          4                   12.01   Oct-Dic 2017
20  2017          3                    8.34  Jul-Sept 2017
21  2017          2                    7.16   Abr-Jun 2017
22  2017          1                    6.62   Ene-Mar 2017
23  2016          4                    6.34   Oct-Dic 2016
24  2016          3                    5.94  Jul-Sept 2016
25  2016          2                    5.42   Abr-Jun 2016
26  2016          1                    5.08   Ene-Mar 2016
27  2015          4                    4.99   Oct-Dic 2015
28  2015          3                    4.79  Jul-Sept 2015
29  2015          2                    4.55   Abr-Jun 2015
30  2015          1                    4.35   Ene-Mar 2015
31  2014          4                    4.16   Oct-Dic 2014
32  2014          3                    3.87  Jul-Sept 2014
33  2014          2                    3.76   Abr-Jun 2014
34  2014          1                    3.62   Ene-Mar 2014

# 4 dataset Internet_Ingresos.csv

Se instancia el dataset como un dataframe en la variable ingresos

In [70]:
ingresos = pd.read_csv('datasets/Internet_Ingresos.csv')
ingresos

Año  Trimestre Ingresos (miles de pesos)        Periodo
0   2022          3                67.055.930  Jul-Sept 2022
1   2022          2                60.335.724   Abr-Jun 2022
2   2022          1                55.589.997   Ene-Mar 2022
3   2021          4                45.467.887   Oct-Dic 2021
4   2021          3                42.999.944  Jul-Sept 2021
5   2021          2                38.239.667   Abr-Jun 2021
6   2021          1                36.676.371   Ene-Mar 2021
7   2020          4                33.539.703   Oct-Dic 2020
8   2020          3                31.997.445  Jul-Sept 2020
9   2020          2                32.102.476   Abr-Jun 2020
10  2020          1                29.946.216   Ene-Mar 2020
11  2019          4                24.169.251   Oct-Dic 2019
12  2019          3                21.652.748  Jul-Sept 2019
13  2019          2                20.743.118   Abr-Jun 2019
14  2019          1                20.207.414   Ene-Mar 2019
15  2018          4                16.637.687   Oct-Dic 2018
16  2018          3                15.410.981  Jul-Sept 2018
17  2018          2                14.319.467   Abr-Jun 2018
18  2018          1                13.171.459   Ene-Mar 2018
19  2017          4                11.226.127   Oct-Dic 2017
20  2017          3                10.065.998  Jul-Sept 2017
21  2017          2                 9.678.647   Abr-Jun 2017
22  2017          1                 8.701.201   Ene-Mar 2017
23  2016          4                 7.483.980   Oct-Dic 2016
24  2016          3                 6.912.442  Jul-Sept 2016
25  2016          2                 6.534.241   Abr-Jun 2016
26  2016          1                 5.936.845   Ene-Mar 2016
27  2015          4                 5.376.899   Oct-Dic 2015
28  2015          3                 5.153.739  Jul-Sept 2015
29  2015          2                 4.701.791   Abr-Jun 2015
30  2015          1                 4.876.385   Ene-Mar 2015
31  2014          4                 3.950.441   Oct-Dic 2014
32  2014          3                 3.478.638  Jul-Sept 2014
33  2014          2                 3.270.816   Abr-Jun 2014
34  2014          1                 2.984.054   Ene-Mar 2014

In [74]:
ingresos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Año                        35 non-null     int64 
 1   Trimestre                  35 non-null     int64 
 2   Ingresos (miles de pesos)  35 non-null     object
 3   Periodo                    35 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.2+ KB


Se analiza si hay datos duplicados

In [75]:
duplicados = ingresos.duplicated(subset=['Periodo'], keep=False)
filas_duplicadas = ingresos[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Año, Trimestre, Ingresos (miles de pesos), Periodo]
Index: []

Se cambia el tipo de dato de la columna Ingresos (miles de pesos) de object a tipo entero

In [76]:
ingresos['Ingresos (miles de pesos)'] = ingresos['Ingresos (miles de pesos)'].str.replace('.', '').astype(int)

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\2056232797.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  ingresos['Ingresos (miles de pesos)'] = ingresos['Ingresos (miles de pesos)'].str.replace('.', '').astype(int)


In [77]:
ingresos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Año                        35 non-null     int64 
 1   Trimestre                  35 non-null     int64 
 2   Ingresos (miles de pesos)  35 non-null     int32 
 3   Periodo                    35 non-null     object
dtypes: int32(1), int64(2), object(1)
memory usage: 1.1+ KB


In [78]:
ingresos

Año  Trimestre  Ingresos (miles de pesos)        Periodo
0   2022          3                   67055930  Jul-Sept 2022
1   2022          2                   60335724   Abr-Jun 2022
2   2022          1                   55589997   Ene-Mar 2022
3   2021          4                   45467887   Oct-Dic 2021
4   2021          3                   42999944  Jul-Sept 2021
5   2021          2                   38239667   Abr-Jun 2021
6   2021          1                   36676371   Ene-Mar 2021
7   2020          4                   33539703   Oct-Dic 2020
8   2020          3                   31997445  Jul-Sept 2020
9   2020          2                   32102476   Abr-Jun 2020
10  2020          1                   29946216   Ene-Mar 2020
11  2019          4                   24169251   Oct-Dic 2019
12  2019          3                   21652748  Jul-Sept 2019
13  2019          2                   20743118   Abr-Jun 2019
14  2019          1                   20207414   Ene-Mar 2019
15  2018          4                   16637687   Oct-Dic 2018
16  2018          3                   15410981  Jul-Sept 2018
17  2018          2                   14319467   Abr-Jun 2018
18  2018          1                   13171459   Ene-Mar 2018
19  2017          4                   11226127   Oct-Dic 2017
20  2017          3                   10065998  Jul-Sept 2017
21  2017          2                    9678647   Abr-Jun 2017
22  2017          1                    8701201   Ene-Mar 2017
23  2016          4                    7483980   Oct-Dic 2016
24  2016          3                    6912442  Jul-Sept 2016
25  2016          2                    6534241   Abr-Jun 2016
26  2016          1                    5936845   Ene-Mar 2016
27  2015          4                    5376899   Oct-Dic 2015
28  2015          3                    5153739  Jul-Sept 2015
29  2015          2                    4701791   Abr-Jun 2015
30  2015          1                    4876385   Ene-Mar 2015
31  2014          4                    3950441   Oct-Dic 2014
32  2014          3                    3478638  Jul-Sept 2014
33  2014          2                    3270816   Abr-Jun 2014
34  2014          1                    2984054   Ene-Mar 2014

# 5 dataset AccesosaInternetfijoporvelocidaddebajadaylocalidad_2776171689464891656.csv

Se instancia el dataset como un dataframe en la variable accesos_a_internet

In [82]:
accesos_a_internet = pd.read_csv('Datasets/AccesosaInternetfijoporvelocidaddebajadaylocalidad_2776171689464891656.csv')
accesos_a_internet

Provincia      Partido                           Localidad  \
0     BUENOS AIRES   25 de Mayo                          25 de Mayo   
1     BUENOS AIRES   25 de Mayo                     Agustín Mosconi   
2     BUENOS AIRES   25 de Mayo                           Del Valle   
3     BUENOS AIRES   25 de Mayo                           Ernestina   
4     BUENOS AIRES   25 de Mayo                   Gobernador Ugarte   
...            ...          ...                                 ...   
3093       TUCUMAN   Tafí Viejo  Villa Mariano Moreno - El Colmenar   
3094       TUCUMAN      Trancas                San Pedro de Colalao   
3095       TUCUMAN      Trancas                   Villa  de Trancas   
3096       TUCUMAN  Yerba Buena                       Villa Carmela   
3097       TUCUMAN  Yerba Buena            Yerba Buena - Marcos Paz   

     Link Indec Otros  0,256 mbps  0,375 mbps 0,5 mbps  0,512 mbps  \
0       6854100   NaN         NaN         NaN        2         NaN   
1       6854010   NaN         NaN         NaN      NaN         NaN   
2       6854020   NaN         NaN         NaN        1         NaN   
3       6854030   NaN         NaN         NaN      NaN         NaN   
4       6854040   NaN         NaN         NaN      NaN         NaN   
...         ...   ...         ...         ...      ...         ...   
3093   90105100   NaN         NaN         NaN      NaN         NaN   
3094   90112020   NaN         NaN         NaN      NaN         NaN   
3095   90112030   NaN         NaN         NaN      NaN         NaN   
3096   90119020   NaN         NaN         NaN      NaN         NaN   
3097   90119030   176         NaN         NaN      NaN         NaN   

      0,625 mbps  ... 75 mbps 78 mbps  80 mbps 82 mbps 83 mbps  85 mbps  \
0            NaN  ...     NaN     NaN      9.0     NaN     NaN      NaN   
1            NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
2            NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
3            NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
4            NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
...          ...  ...     ...     ...      ...     ...     ...      ...   
3093         NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
3094         NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
3095         NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
3096         NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   
3097         NaN  ...     NaN     NaN      NaN     NaN     NaN      NaN   

      90 mbps 92 mbps  95 mbps 100 mbps  
0         NaN     NaN      NaN      NaN  
1         NaN     NaN      NaN      NaN  
2         NaN     NaN      NaN      NaN  
3         NaN     NaN      NaN      NaN  
4         NaN     NaN      NaN      NaN  
...       ...     ...      ...      ...  
3093      NaN     NaN      NaN      304  
3094      NaN     NaN      NaN      NaN  
3095      NaN     NaN      NaN      NaN  
3096      NaN     NaN      NaN      NaN  
3097      NaN     NaN      NaN    6,556  

[3098 rows x 83 columns]

In [83]:
accesos_a_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3098 entries, 0 to 3097
Data columns (total 83 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Provincia   3098 non-null   object 
 1   Partido     3098 non-null   object 
 2   Localidad   3098 non-null   object 
 3   Link Indec  3098 non-null   object 
 4   Otros       956 non-null    object 
 5   0,256 mbps  29 non-null     float64
 6   0,375 mbps  1 non-null      float64
 7   0,5 mbps    643 non-null    object 
 8   0,512 mbps  524 non-null    float64
 9   0,625 mbps  1 non-null      float64
 10  0,75 mbps   284 non-null    object 
 11  1 mbps      931 non-null    object 
 12  1,25 mbps   1 non-null      float64
 13  1,5 mbps    16 non-null     object 
 14  2 mbps      741 non-null    object 
 15  2,2 mbps    1 non-null      float64
 16  2,5 mbps    3 non-null      float64
 17  3 mbps      1388 non-null   object 
 18  3,3 mbps    1 non-null      float64
 19  3,5 mbps    373 non-null   

Se analiza si hay datos repetidos

In [84]:
duplicados = accesos_a_internet.duplicated(subset=['Provincia', 'Partido', 'Localidad'], keep=False)
filas_duplicadas = accesos_a_internet[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Provincia, Partido, Localidad, Link Indec, Otros, 0,256 mbps, 0,375 mbps, 0,5 mbps, 0,512 mbps, 0,625 mbps, 0,75 mbps, 1 mbps, 1,25 mbps, 1,5 mbps, 2 mbps, 2,2 mbps, 2,5 mbps, 3 mbps, 3,3 mbps, 3,5 mbps, 4 mbps, 4,5 mbps, 5 mbps, 6 mbps, 6,4 mbps, 7 mbps, 7,5 mbps, 8 mbps, 9 mbps, 10 mbps, 11 mbps, 12 mbps, 13 mbps, 14 mbps, 15 mbps, 16 mbps, 17 mbps, 18 mbps, 19 mbps, 20 mbps, 21 mbps, 22 mbps, 23 mbps, 24 mbps, 25 mbps, 25,1 mbps, 25,11 mbps, 25,5 mbps, 26 mbps, 30 mbps, 31 mbps, 32 mbps, 34 mbps, 35 mbps, 36 mbps, 38 mbps, 39 mbps, 40 mbps, 41 mbps, 45 mbps, 46 mbps, 49 mbps, 50 mbps, 55 mbps, 58 mbps, 59 mbps, 60 mbps, 61 mbps, 62 mbps, 64 mbps, 65 mbps, 66 mbps, 70 mbps, 75 mbps, 78 mbps, 80 mbps, 82 mbps, 83 mbps, 85 mbps, 90 mbps, 92 mbps, 95 mbps, 100 mbps]
Index: []

[0 rows x 83 columns]

CAMBIAR LAS COLUMNAS DE MBPS QUE SON OBJECT A FLOAT

Se crea una variable que contenga todas las columnas mbps

In [85]:
columnas_convertir = [col for col in accesos_a_internet.columns if col not in ['Provincia', 'Partido', 'Localidad', 'Link Indec', 'Otros']]

Para cambiar el tipo de columna, se itera por cada una de ellas, con el condicionante if tomamos solamente las que son de tipo object, una vez hecho eso se les cambia la ',' que aparece un algunas filas por un '.' para que sea posible la transformación a float y por último se realiza dicha transformación

In [86]:
for columna in columnas_convertir:
    if accesos_a_internet[columna].dtype == object:
        accesos_a_internet[columna] = accesos_a_internet[columna].str.replace(',', '.')
        accesos_a_internet[columna] = pd.to_numeric(accesos_a_internet[columna])

In [87]:
accesos_a_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3098 entries, 0 to 3097
Data columns (total 83 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Provincia   3098 non-null   object 
 1   Partido     3098 non-null   object 
 2   Localidad   3098 non-null   object 
 3   Link Indec  3098 non-null   object 
 4   Otros       956 non-null    object 
 5   0,256 mbps  29 non-null     float64
 6   0,375 mbps  1 non-null      float64
 7   0,5 mbps    643 non-null    float64
 8   0,512 mbps  524 non-null    float64
 9   0,625 mbps  1 non-null      float64
 10  0,75 mbps   284 non-null    float64
 11  1 mbps      931 non-null    float64
 12  1,25 mbps   1 non-null      float64
 13  1,5 mbps    16 non-null     float64
 14  2 mbps      741 non-null    float64
 15  2,2 mbps    1 non-null      float64
 16  2,5 mbps    3 non-null      float64
 17  3 mbps      1388 non-null   float64
 18  3,3 mbps    1 non-null      float64
 19  3,5 mbps    373 non-null   

# 6 dataset Datasets/Internet_BAF (1).csv

Se instancia el dataset como un dataframe en la variable baf

In [88]:
baf = pd.read_csv('Datasets/Internet_BAF (1).csv')
baf

Año  Trimestre            Provincia Banda ancha fija Dial up      Total
0    2022          3         Buenos Aires        4.715.469   6.199  4.721.668
1    2022          3      Capital Federal        1.545.534   2.145  1.547.679
2    2022          3            Catamarca           70.292       1     70.293
3    2022          3                Chaco          144.141       5    144.146
4    2022          3               Chubut          164.874     904    165.778
..    ...        ...                  ...              ...     ...        ...
835  2014          1           Santa Cruz           26.304     460     26.764
836  2014          1             Santa Fe          506.000     612    506.612
837  2014          1  Santiago Del Estero           37.124       9     37.133
838  2014          1     Tierra Del Fuego           27.272     766     28.038
839  2014          1              Tucumán          129.944      88    130.032

[840 rows x 6 columns]

In [89]:
baf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Año               840 non-null    int64 
 1   Trimestre         840 non-null    int64 
 2   Provincia         840 non-null    object
 3   Banda ancha fija  840 non-null    object
 4   Dial up           838 non-null    object
 5   Total             840 non-null    object
dtypes: int64(2), object(4)
memory usage: 39.5+ KB


Se analiza si hay datos repetidos

In [90]:
duplicados = baf.duplicated(subset=['Año', 'Trimestre', 'Provincia'], keep=False)
filas_duplicadas = baf[duplicados]
filas_duplicadas

Empty DataFrame
Columns: [Año, Trimestre, Provincia, Banda ancha fija, Dial up, Total]
Index: []

Se cambia el tipo de dato de las columnas Banda ancha fija,	Dial up y Total de object a int

In [91]:
baf['Banda ancha fija'] = baf['Banda ancha fija'].str.replace('.', '').astype(int)

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\729599289.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  baf['Banda ancha fija'] = baf['Banda ancha fija'].str.replace('.', '').astype(int)


Para Dial Up se cambia los valores - 0 por 0

In [107]:
filtro = baf['Dial up'] == '- 0'
filas_dial_up_negativo = baf[filtro]
print(filas_dial_up_negativo)

Empty DataFrame
Columns: [Año, Trimestre, Provincia, Banda ancha fija, Dial up, Total]
Index: []


In [104]:
baf['Dial up'] = baf['Dial up'].str.replace('- 0', '0')

se cambia los valores nulos por 0

In [124]:
baf['Dial up'] = baf['Dial up'].fillna(0)

In [119]:
baf['Dial up'] = baf['Dial up'].str.replace('.', '').str.replace(',', '')

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\1352199786.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  baf['Dial up'] = baf['Dial up'].str.replace('.', '').str.replace(',', '')


In [125]:
baf['Dial up'] = baf['Dial up'].astype(int)

In [128]:
baf['Total'] = baf['Total'].str.replace('.', '').astype(int)

C:\Users\I5\AppData\Local\Temp\ipykernel_11176\4200170920.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  baf['Total'] = baf['Total'].str.replace('.', '').astype(int)


In [129]:
baf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Año               840 non-null    int64 
 1   Trimestre         840 non-null    int64 
 2   Provincia         840 non-null    object
 3   Banda ancha fija  840 non-null    int32 
 4   Dial up           840 non-null    int32 
 5   Total             840 non-null    int32 
dtypes: int32(3), int64(2), object(1)
memory usage: 29.7+ KB


In [177]:
baf2 = baf

In [182]:
baf2

Año  Trimestre            Provincia  Banda ancha fija  Dial up    Total
0    2022          3         Buenos Aires           4715469     6199  4721668
1    2022          3      Capital Federal           1545534     2145  1547679
2    2022          3            Catamarca             70292        1    70293
3    2022          3                Chaco            144141        5   144146
4    2022          3               Chubut            164874      904   165778
..    ...        ...                  ...               ...      ...      ...
835  2014          1           Santa Cruz             26304      460    26764
836  2014          1             Santa Fe            506000      612   506612
837  2014          1  Santiago Del Estero             37124        9    37133
838  2014          1     Tierra Del Fuego             27272      766    28038
839  2014          1              Tucumán            129944       88   130032

[840 rows x 6 columns]

Se agrupan todos los datos por año y trimestre, sin tener en cuenta la provincia

In [180]:
baf = baf.groupby(['Año', 'Trimestre'], as_index=False).sum()


In [181]:

baf

Año  Trimestre  Banda ancha fija  Dial up     Total
0   2014          1           6362108    36290   6398398
1   2014          2           6428329    36139   6464468
2   2014          3           6559264    36007   6595271
3   2014          4           6559172    39324   6598496
4   2015          1           6699714    38018   6737732
5   2015          2           6783279    32909   6816188
6   2015          3           6902267    32801   6935068
7   2015          4           6952289    32542   6984831
8   2016          1           6874704    32652   6907356
9   2016          2           7097604    32475   7130079
10  2016          3           7178340    28610   7206950
11  2016          4           7223128    28545   7251673
12  2017          1           7277314    28540   7305854
13  2017          2           7401134    28530   7429664
14  2017          3           7696594    28349   7724943
15  2017          4           7842778    27444   7870222
16  2018          1           8009981    27072   8037053
17  2018          2           8083533    26911   8110444
18  2018          3           8320223    26812   8347035
19  2018          4           8451841    21814   8473655
20  2019          1           8626323    21812   8648135
21  2019          2           8938427    21754   8960181
22  2019          3           9142891    21793   9164684
23  2019          4           8783053    10128   8793181
24  2020          1           8802435     9991   8812426
25  2020          2           9021040    10016   9031056
26  2020          3           9346183    10016   9356199
27  2020          4           9561546    10016   9571562
28  2021          1           9637956    10016   9647972
29  2021          2           9852702    10382   9863084
30  2021          3          10075184    10357  10085541
31  2021          4          10476933    12861  10489794
32  2022          1          10611390    12619  10624009
33  2022          2          10946248    12436  10958684
34  2022          3          11078691    12437  11091128

Se crean archivos .csv a partir de los dataframes procesados

In [172]:
#conectividad.to_csv('conectividad.csv', index = False)

In [132]:
#penetracion.to_csv('penetracion.csv', index = False)

In [133]:
#historico_velocidad_internet.to_csv('historico_velocidad_internet.csv', index = False)

In [134]:
#ingresos.to_csv('ingresos.csv', index = False)

In [135]:
#accesos_a_internet.to_csv('accesos_a_internet.csv', index = False)

In [183]:
#baf.to_csv('baf.csv', index = False)

In [184]:
#baf2.to_csv('baf_or.csv', index = False)